sudo docker build -t images.k11e.org/jlk/find_main_species:v1.1.0 .

sudo docker run --rm -v /home/jianglikun/MGS/zhenghe/docker_test/find_main_species/:/home/jianglikun/MGS/zhenghe/docker_test/find_main_species/ images.k11e.org/jlk/find_main_species:v1.1.0 bash Gnerate_Dna_data_frame.sh -d /home/jianglikun/MGS/zhenghe/docker_test/find_main_species/blastn_out -i /home/jianglikun/MGS/zhenghe/docker_test/find_main_species/ASD.40samples_clusters -a assembly.id.txt -g 4904MG.info.txt -o /home/jianglikun/MGS/zhenghe/docker_test/find_main_species/oooo
